/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Devtools: typeof import('./src/components/devtools/index.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Image: typeof import('primevue/image')['default']
    JsonViewer: typeof import('./src/components/JsonViewer.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Page: typeof import('./src/components/devtools/Page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Selection: typeof import('./src/components/devtools/Selection/index.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Trigger: typeof import('./src/components/trigger.vue')['default']
    Workspace: typeof import('./src/components/devtools/Workspace/index.vue')['default']
    Yjs: typeof import('./src/components/devtools/Yjs.vue')['default']
  }
}
